### ISSUE TITLE
Error: there is already a client

### ISSUE THREAD

**Issue by geoffreylitt** [jedahan/room-server#8]
When I try to run the [room-client browser example](https://github.com/jedahan/room-client/blob/3b6cb60c9b7881dd9a57dc82682625b6cc254f79/examples/index.html) against this room-server, the first few assert calls work, but when it starts trying to poll with select queries, the server throws the error below. (If I comment out the error handling code everything works fine)

```
 Error: there is already a client whose id is _1
      at RoomDB.connect (/Users/glitt/personal-dev/research/room-server/node_modules/roomdb/dist/roomdb.js:297:13)
      at Object.client (/Users/glitt/personal-dev/research/room-server/lib/room.js:11:45)
      at /Users/glitt/personal-dev/research/room-server/lib/httpServer.js:20:39
      at dispatch (/Users/glitt/personal-dev/research/room-server/node_modules/koa-compose/index.js:42:32)
      at next (/Users/glitt/personal-dev/research/room-server/node_modules/koa-compose/index.js:43:18)
      at /Users/glitt/personal-dev/research/room-server/lib/httpServer.js:14:9
      at dispatch (/Users/glitt/personal-dev/research/room-server/node_modules/koa-compose/index.js:42:32)
      at next (/Users/glitt/personal-dev/research/room-server/node_modules/koa-compose/index.js:43:18)
      at /Users/glitt/personal-dev/research/room-server/node_modules/koa-body/index.js:98:14
      at <anonymous>
```

It seems like this is because of how `lib/room.js` in this repository is interacting with RoomDB in terms of client ID management. Maybe this is one of the known rough spots that you were referring to @jedahan ?  

I don't have enough context about what client IDs are for in this system to know what the appropriate fix is, but if you'd be willing to explain that piece, I would be happy to work on a PR to fix.

**Comment by jedahan** [comment]
I just pushed changes to room-server and room-client to remove the notion of ids, it really isn't needed at this level. can you try again?

**Comment by geoffreylitt** [comment]
Your fix commit worked, thanks!

Subsequent commits seem to have broken the http server though, so I put out #9 as a PR to fix.
